[general]
import = [
    "~/.config/alacritty/themes/themes/noctis_lux.toml"
]

[env]
# Set the COLORTERM environment variable to indicate true color support
term = "xterm-256color" # This might be needed for compatibility
COLORTERM = "truecolor"

[scrolling]
history = 10000
multiplier = 3 # Default is 3

[font]
size = 12.0

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[font.bold]
family = "Iosevka Nerd Font"
style = "Bold"

[font.italic]
family = "Iosevka Nerd Font"
style = "Italic"

[font.bold_italic]
family = "Iosevka Nerd Font"
style = "Bold Italic"
